### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by DaltonHart** [DoctorZulu/Tamagotchi#1]
Project meets requirements. I will be providing some feedback in the following messages of this issue on how you can improve your application prior to the job search.

**Comment by DaltonHart** [comment]
### Visual Feedback

Honestly I do not have much to add to the visual feedback portion of your review. I think you did a great job making it look like a Tamagotchi and behave like one. I think some additional animations to your buttons and making it scale a bit better on different devices could be beneficial using media queries. You can view some information on them [HERE](https://css-tricks.com/a-complete-guide-to-css-media-queries/).

Some feedback on your css code would be indentation. It is a bit all over the place. For example: 

```css
  #dead {
    position: absolute;
    display: inline-block;
    background: url('Media/Other.png') no-repeat -695px -235px;
	  width: 48px;  /* <-- What is going on here? */
	  height: 37px;
    left: 70px;
    top: 70px;
    animation: none;
    
    /* so much open space after this animation */
    
   
    }
```

You also have zero comments or organization in your css file. It would be beneficial to or organize your css into chunks and create headers for it as well. For example: 

```css
/* === Header  === */
/* === Device === */
```

Stuff like that will make your future employer very happy and without them be hard to land a position in a formal code review.
